// website/src/content/docs/react/code-examples/headless/print-example.tsx
'use client'

import { createPluginRegistration } from '@embedpdf/core'
import { EmbedPDF } from '@embedpdf/core/react'
import { usePdfiumEngine } from '@embedpdf/engines/react'
import { useState } from 'react'
import {
  Viewport,
  ViewportPluginPackage,
} from '@embedpdf/plugin-viewport/react'
import { Scroller, ScrollPluginPackage } from '@embedpdf/plugin-scroll/react'
import {
  DocumentContent,
  DocumentManagerPluginPackage,
} from '@embedpdf/plugin-document-manager/react'
import { RenderLayer, RenderPluginPackage } from '@embedpdf/plugin-render/react'
import { usePrint, PrintPluginPackage } from '@embedpdf/plugin-print/react'
import { Loader2, Printer } from 'lucide-react'

const plugins = [
  createPluginRegistration(DocumentManagerPluginPackage, {
    initialDocuments: [{ url: 'https://raw.githubusercontent.com/arnon3339/pubme/main/pdf/Digital_Inno_Cover.pdf' }],
  }),
  createPluginRegistration(ViewportPluginPackage),
  createPluginRegistration(ScrollPluginPackage),
  createPluginRegistration(RenderPluginPackage),
  createPluginRegistration(PrintPluginPackage),
]

const PrintToolbar = ({ documentId }: { documentId: string }) => {
  const { provides: print } = usePrint(documentId)
  const [isPrinting, setIsPrinting] = useState(false)

  const handlePrint = () => {
    if (!print || isPrinting) return
    setIsPrinting(true)

    const printTask = print.print()

    printTask.wait(
      () => setIsPrinting(false),
      (error) => {
        console.error('Failed to print document:', error)
        setIsPrinting(false)
      },
    )
  }

  return (
    <div className="flex items-center gap-3 border-b border-gray-300 bg-gray-100 px-3 py-2 dark:border-gray-700 dark:bg-gray-800">
      <button
        onClick={handlePrint}
        disabled={!print || isPrinting}
        className="inline-flex items-center gap-2 rounded-md bg-blue-500 px-3 py-1.5 text-sm font-medium text-white shadow-sm transition-all hover:bg-blue-600 disabled:cursor-not-allowed disabled:opacity-50"
      >
        {isPrinting ? (
          <>
            <Loader2 size={16} className="animate-spin" />
            Preparing...
          </>
        ) : (
          <>
            <Printer size={16} />
            Print Document
          </>
        )}
      </button>
      {!isPrinting && (
        <span className="text-xs text-gray-600 dark:text-gray-300">
          Opens your system print dialog
        </span>
      )}
      {isPrinting && (
        <span className="animate-pulse text-xs text-blue-600 dark:text-blue-400">
          Rendering pages for print...
        </span>
      )}
    </div>
  )
}

export const PDFViewer = () => {
  const { engine, isLoading } = usePdfiumEngine()

  if (isLoading || !engine) {
    return (
      <div className="overflow-hidden rounded-lg border border-gray-300 bg-white dark:border-gray-700 dark:bg-gray-900">
        <div className="flex h-[400px] items-center justify-center">
          <div className="flex items-center gap-2 text-gray-500 dark:text-gray-400">
            <Loader2 size={20} className="animate-spin" />
            <span className="text-sm">Loading PDF Engine...</span>
          </div>
        </div>
      </div>
    )
  }

  return (
    <EmbedPDF engine={engine} plugins={plugins}>
      {({ activeDocumentId }) =>
        activeDocumentId && (
          <DocumentContent documentId={activeDocumentId}>
            {({ isLoaded }) =>
              isLoaded && (
                <div className="overflow-hidden rounded-lg border border-gray-300 bg-white shadow-sm dark:border-gray-700 dark:bg-gray-900">
                  {/* Toolbar */}
                  <PrintToolbar documentId={activeDocumentId} />

                  {/* PDF Viewer Area */}
                  <div className="relative h-[400px] sm:h-[500px]">
                    <Viewport
                      documentId={activeDocumentId}
                      className="absolute inset-0 bg-gray-200 dark:bg-gray-800"
                    >
                      <Scroller
                        documentId={activeDocumentId}
                        renderPage={({ pageIndex }) => (
                          <RenderLayer
                            documentId={activeDocumentId}
                            pageIndex={pageIndex}
                          />
                        )}
                      />
                    </Viewport>
                  </div>
                </div>
              )
            }
          </DocumentContent>
        )
      }
    </EmbedPDF>
  )
}

// examples/svelte-tailwind/src/examples/viewer/print-example.svelte
<script lang="ts">
  import {
    PDFViewer,
    type EmbedPdfContainer,
    type PluginRegistry,
    type PrintPlugin,
    type PrintScope,
  } from '@embedpdf/svelte-pdf-viewer';
  import { Printer } from 'lucide-svelte';

  interface Props {
    themePreference?: 'light' | 'dark';
  }

  let { themePreference = 'light' }: Props = $props();

  let container = $state<EmbedPdfContainer | null>(null);
  let docPrint = $state<PrintScope | null>(null);
  let isPrinting = $state(false);

  const handleInit = (c: EmbedPdfContainer) => {
    container = c;
  };

  const handleReady = (registry: PluginRegistry) => {
    const printPlugin = registry.getPlugin<PrintPlugin>('print')?.provides();
    if (printPlugin) {
      docPrint = printPlugin.forDocument('ebook');
    }
  };

  $effect(() => {
    container?.setTheme({ preference: themePreference });
  });

  const handlePrint = () => {
    if (isPrinting || !docPrint) return;

    isPrinting = true;

    docPrint.print().wait(
      () => (isPrinting = false),
      (err) => {
        console.error('Print failed', err);
        isPrinting = false;
      },
    );
  };
</script>

<div class="flex flex-col gap-4">
  <!-- External Controls -->
  <div
    class="flex flex-wrap items-center justify-between gap-4 rounded-lg border border-gray-200 bg-gray-50 p-4 dark:border-gray-700 dark:bg-gray-800"
  >
    <div class="flex items-center gap-4">
      <button
        type="button"
        onclick={handlePrint}
        disabled={isPrinting}
        class="flex items-center gap-2 rounded bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:bg-gray-400 dark:disabled:bg-gray-700"
      >
        <Printer size={18} />
        {isPrinting ? 'Preparing...' : 'Print Document'}
      </button>

      {#if isPrinting}
        <span class="animate-pulse text-sm text-gray-500 dark:text-gray-400">
          Generating print version...
        </span>
      {/if}
    </div>
  </div>

  <!-- Viewer -->
  <div
    class="h-[500px] w-full overflow-hidden rounded-xl border border-gray-300 shadow-lg dark:border-gray-600"
  >
    <PDFViewer
      oninit={handleInit}
      onready={handleReady}
      config={{
        theme: { preference: themePreference },
        documentManager: {
          initialDocuments: [
            {
              url: 'https://raw.githubusercontent.com/arnon3339/pubme/main/pdf/Digital_Inno_Cover.pdf',
              documentId: 'ebook',
            },
          ],
        },
      }}
      style="width: 100%; height: 100%;"
    />
  </div>
</div>
