// packages/plugin-annotation/src/svelte/components/annotations/FreeText.svelte
<!-- Free-text.svelte -->
<script lang="ts">
  import {
    type PdfFreeTextAnnoObject,
    PdfVerticalAlignment,
    fontRefToCss,
    textAlignmentToCss,
  } from '@embedpdf/models';
  import type { TrackedAnnotation } from '@embedpdf/plugin-annotation';
  import { useAnnotationCapability } from '../../hooks';

  // ---------- props ----------
  interface FreeTextProps {
    documentId: string;
    isSelected: boolean;
    isEditing: boolean;
    annotation: TrackedAnnotation<PdfFreeTextAnnoObject>;
    pageIndex: number;
    scale: number;
    onClick?: (e: MouseEvent | TouchEvent) => void;
    onDoubleClick?: (e: MouseEvent) => void;
  }

  let { documentId, isSelected, isEditing, annotation, pageIndex, scale, onClick }: FreeTextProps =
    $props();

  // ---------- capabilities ----------
  const annotationCapability = useAnnotationCapability();

  // Get scoped API for this document
  const annotationProvides = $derived(
    annotationCapability.provides ? annotationCapability.provides.forDocument(documentId) : null,
  );

  // ---------- refs / state ----------
  let editorRef: HTMLSpanElement | null = null;
  let isIOS = $state(false);

  // Focus and move caret to end when entering edit mode
  $effect(() => {
    if (!isEditing || !editorRef) return;
    editorRef.focus();

    const selection = window.getSelection?.();
    if (!selection) return;

    const range = document.createRange();
    range.selectNodeContents(editorRef);
    range.collapse(false);
    selection.removeAllRanges();
    selection.addRange(range);
  });

  // One-time iOS detection (prevents zoom by font-size compensation)
  $effect.pre(() => {
    try {
      const nav = navigator as any;
      const ios =
        /iPad|iPhone|iPod/.test(navigator.userAgent) ||
        (navigator.platform === 'MacIntel' && nav?.maxTouchPoints > 1);
      isIOS = ios;
    } catch {
      isIOS = false;
    }
  });

  // Persist contents on blur
  function handleBlur() {
    if (!annotationProvides || !editorRef) return;
    annotationProvides.updateAnnotation(pageIndex, annotation.object.id, {
      contents: editorRef.innerText,
    });
  }

  // ---------- iOS zoom compensation ----------
  const computedFontPx = $derived(annotation.object.fontSize * scale);
  const MIN_IOS_FOCUS_FONT_PX = 16;
  const needsComp = $derived(
    isIOS && isEditing && computedFontPx > 0 && computedFontPx < MIN_IOS_FOCUS_FONT_PX,
  );
  const adjustedFontPx = $derived(needsComp ? MIN_IOS_FOCUS_FONT_PX : computedFontPx);
  const scaleComp = $derived(needsComp ? computedFontPx / MIN_IOS_FOCUS_FONT_PX : 1);
  const invScalePercent = $derived(needsComp ? 100 / scaleComp : 100);

  // ---------- derived sizes ----------
  const outerW = $derived(annotation.object.rect.size.width * scale);
  const outerH = $derived(annotation.object.rect.size.height * scale);

  const justify = $derived(
    annotation.object.verticalAlign === PdfVerticalAlignment.Top
      ? 'flex-start'
      : annotation.object.verticalAlign === PdfVerticalAlignment.Middle
        ? 'center'
        : 'flex-end',
  );
</script>

<!-- Outer positioned container -->
<div
  style:position="absolute"
  style:width={`${outerW}px`}
  style:height={`${outerH}px`}
  style:z-index={2}
  style:cursor={isSelected && !isEditing ? 'move' : 'default'}
  style:pointer-events={isSelected && !isEditing ? 'none' : 'auto'}
  onpointerdown={onClick}
  ontouchstart={onClick}
>
  <!-- Editable span -->
  <span
    bind:this={editorRef}
    tabindex="0"
    contenteditable={isEditing}
    onblur={handleBlur}
    style:display="flex"
    style:flex-direction="column"
    style:justify-content={justify}
    style:color={annotation.object.fontColor}
    style:font-size={`${adjustedFontPx}px`}
    style:font-family={fontRefToCss(annotation.object.fontFamily)}
    style:text-align={textAlignmentToCss(annotation.object.textAlign)}
    style:background-color={annotation.object.backgroundColor}
    style:opacity={annotation.object.opacity}
    style:width={needsComp ? `${invScalePercent}%` : '100%'}
    style:height={needsComp ? `${invScalePercent}%` : '100%'}
    style:line-height="1.18"
    style:overflow="hidden"
    style:cursor={isEditing ? 'text' : 'pointer'}
    style:outline="none"
    style:transform={needsComp ? `scale(${scaleComp})` : undefined}
    style:transform-origin="top left">{annotation.object.contents}</span
  >
</div>

// packages/plugin-annotation/src/shared/components/annotations/free-text.tsx
import {
  MouseEvent,
  TouchEvent,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  suppressContentEditableWarningProps,
} from '@framework';
import {
  PdfFreeTextAnnoObject,
  PdfVerticalAlignment,
  fontRefToCss,
  textAlignmentToCss,
} from '@embedpdf/models';
import { useAnnotationCapability } from '../..';
import { TrackedAnnotation } from '@embedpdf/plugin-annotation';

interface FreeTextProps {
  isSelected: boolean;
  isEditing: boolean;
  annotation: TrackedAnnotation<PdfFreeTextAnnoObject>;
  pageIndex: number;
  scale: number;
  onClick?: (e: MouseEvent<HTMLDivElement> | TouchEvent<HTMLDivElement>) => void;
  onDoubleClick?: (event: MouseEvent<HTMLDivElement>) => void;
}

export function FreeText({
  isSelected,
  isEditing,
  annotation,
  pageIndex,
  scale,
  onClick,
}: FreeTextProps) {
  const editorRef = useRef<HTMLSpanElement>(null);
  const { provides: annotationProvides } = useAnnotationCapability();
  const [isIOS, setIsIOS] = useState(false);

  useEffect(() => {
    if (isEditing && editorRef.current) {
      const editor = editorRef.current;
      editor.focus();

      const selection = window.getSelection();
      if (selection) {
        const range = document.createRange();
        range.selectNodeContents(editor);
        range.collapse(false);
        selection.removeAllRanges();
        selection.addRange(range);
      }
    }
  }, [isEditing]);

  useLayoutEffect(() => {
    try {
      const nav = navigator as any;
      const ios =
        /iPad|iPhone|iPod/.test(navigator.userAgent) ||
        (navigator.platform === 'MacIntel' && nav?.maxTouchPoints > 1);
      setIsIOS(ios);
    } catch {
      setIsIOS(false);
    }
  }, []);

  const handleBlur = () => {
    if (!annotationProvides) return;
    if (!editorRef.current) return;
    annotationProvides.updateAnnotation(pageIndex, annotation.object.id, {
      contents: editorRef.current.innerText,
    });
  };

  // iOS zoom prevention: keep focused font-size >= 16px, visually scale down if needed.
  const computedFontPx = annotation.object.fontSize * scale;
  const MIN_IOS_FOCUS_FONT_PX = 16;
  const needsComp =
    isIOS && isEditing && computedFontPx > 0 && computedFontPx < MIN_IOS_FOCUS_FONT_PX;
  const adjustedFontPx = needsComp ? MIN_IOS_FOCUS_FONT_PX : computedFontPx;
  const scaleComp = needsComp ? computedFontPx / MIN_IOS_FOCUS_FONT_PX : 1;
  const invScalePercent = needsComp ? 100 / scaleComp : 100;

  return (
    <div
      style={{
        position: 'absolute',
        width: annotation.object.rect.size.width * scale,
        height: annotation.object.rect.size.height * scale,
        cursor: isSelected && !isEditing ? 'move' : 'default',
        pointerEvents: isSelected && !isEditing ? 'none' : 'auto',
        zIndex: 2,
      }}
      onPointerDown={onClick}
      onTouchStart={onClick}
    >
      <span
        ref={editorRef}
        onBlur={handleBlur}
        tabIndex={0}
        style={{
          color: annotation.object.fontColor,
          fontSize: adjustedFontPx,
          fontFamily: fontRefToCss(annotation.object.fontFamily),
          textAlign: textAlignmentToCss(annotation.object.textAlign),
          flexDirection: 'column',
          justifyContent:
            annotation.object.verticalAlign === PdfVerticalAlignment.Top
              ? 'flex-start'
              : annotation.object.verticalAlign === PdfVerticalAlignment.Middle
                ? 'center'
                : 'flex-end',
          display: 'flex',
          backgroundColor: annotation.object.backgroundColor,
          opacity: annotation.object.opacity,
          width: needsComp ? `${invScalePercent}%` : '100%',
          height: needsComp ? `${invScalePercent}%` : '100%',
          lineHeight: '1.18',
          overflow: 'hidden',
          cursor: isEditing ? 'text' : 'pointer',
          outline: 'none',
          transform: needsComp ? `scale(${scaleComp})` : undefined,
          transformOrigin: 'top left',
        }}
        contentEditable={isEditing}
        {...suppressContentEditableWarningProps}
      >
        {annotation.object.contents}
      </span>
    </div>
  );
}
