// examples/vue-tailwind/src/examples/headless/commands-example.vue
<script setup lang="ts">
import { usePdfiumEngine } from '@embedpdf/engines/vue';
import { EmbedPDF } from '@embedpdf/core/vue';
import { createPluginRegistration, type GlobalStoreState } from '@embedpdf/core';
import {
  DocumentManagerPluginPackage,
  DocumentContent,
} from '@embedpdf/plugin-document-manager/vue';
import {
  ViewportPluginPackage,
  VIEWPORT_PLUGIN_ID,
  type ViewportState,
} from '@embedpdf/plugin-viewport/vue';
import {
  ScrollPluginPackage,
  SCROLL_PLUGIN_ID,
  type ScrollState,
  type ScrollPlugin,
} from '@embedpdf/plugin-scroll/vue';
import { RenderPluginPackage } from '@embedpdf/plugin-render/vue';
import {
  ZoomPluginPackage,
  ZoomMode,
  ZOOM_PLUGIN_ID,
  type ZoomState,
} from '@embedpdf/plugin-zoom/vue';
import { CommandsPluginPackage, type Command } from '@embedpdf/plugin-commands/vue';
import { Loader2 } from 'lucide-vue-next';
import CommandsExampleContent from './commands-example-content.vue';

const { engine, isLoading } = usePdfiumEngine();

// Define app state type
export type State = GlobalStoreState<{
  [ZOOM_PLUGIN_ID]: ZoomState;
  [VIEWPORT_PLUGIN_ID]: ViewportState;
  [SCROLL_PLUGIN_ID]: ScrollState;
}>;

// Define Commands
const myCommands: Record<string, Command<State>> = {
  'nav.prev': {
    id: 'nav.prev',
    label: 'Previous Page',
    shortcuts: ['arrowleft', 'k'],
    action: ({ registry, documentId }) => {
      registry
        .getPlugin<ScrollPlugin>('scroll')
        ?.provides()
        ?.forDocument(documentId)
        .scrollToPreviousPage();
    },
    disabled: ({ state, documentId }) => {
      const scrollState = state.plugins.scroll.documents[documentId];
      return scrollState ? scrollState.currentPage <= 1 : true;
    },
  },
  'nav.next': {
    id: 'nav.next',
    label: 'Next Page',
    shortcuts: ['arrowright', 'j'],
    action: ({ registry, documentId }) => {
      registry
        .getPlugin<ScrollPlugin>('scroll')
        ?.provides()
        ?.forDocument(documentId)
        .scrollToNextPage();
    },
    disabled: ({ state, documentId }) => {
      const scrollState = state.plugins.scroll.documents[documentId];
      return scrollState ? scrollState.currentPage >= scrollState.totalPages : true;
    },
  },
  'doc.alert': {
    id: 'doc.alert',
    label: 'Show Info',
    shortcuts: ['ctrl+i', 'meta+i'],
    action: ({ state, documentId }) => {
      const page = state.plugins.scroll.documents[documentId]?.currentPage;
      if (!page) return;
      alert(`You are currently reading page ${page}`);
    },
  },
};

const plugins = [
  createPluginRegistration(DocumentManagerPluginPackage, {
    initialDocuments: [{ url: 'https://raw.githubusercontent.com/arnon3339/pubme/main/pdf/Digital_Inno_Cover.pdf' }],
  }),
  createPluginRegistration(ViewportPluginPackage),
  createPluginRegistration(ScrollPluginPackage),
  createPluginRegistration(RenderPluginPackage),
  createPluginRegistration(ZoomPluginPackage, {
    defaultZoomLevel: ZoomMode.FitPage,
  }),
  createPluginRegistration(CommandsPluginPackage, {
    commands: myCommands,
  }),
];
</script>

<template>
  <div
    v-if="isLoading || !engine"
    class="overflow-hidden rounded-lg border border-gray-300 bg-white dark:border-gray-700 dark:bg-gray-900"
  >
    <div class="flex h-[400px] items-center justify-center">
      <div class="flex items-center gap-2 text-gray-500 dark:text-gray-400">
        <Loader2 :size="20" class="animate-spin" />
        <span class="text-sm">Loading PDF Engine...</span>
      </div>
    </div>
  </div>
  <EmbedPDF v-else :engine="engine" :plugins="plugins" v-slot="{ activeDocumentId }">
    <DocumentContent
      v-if="activeDocumentId"
      :document-id="activeDocumentId"
      v-slot="{ isLoading: docLoading, isLoaded }"
    >
      <div
        v-if="docLoading"
        class="overflow-hidden rounded-lg border border-gray-300 bg-white dark:border-gray-700 dark:bg-gray-900"
      >
        <div class="flex h-[400px] items-center justify-center">
          <div class="flex items-center gap-2 text-gray-500 dark:text-gray-400">
            <Loader2 :size="20" class="animate-spin" />
            <span class="text-sm">Loading document...</span>
          </div>
        </div>
      </div>
      <div
        v-if="isLoaded"
        class="overflow-hidden rounded-lg border border-gray-300 bg-white shadow-sm dark:border-gray-700 dark:bg-gray-900"
      >
        <CommandsExampleContent :document-id="activeDocumentId" />
      </div>
    </DocumentContent>
  </EmbedPDF>
</template>

// website/src/content/docs/react/code-examples/headless/commands-example.tsx
'use client'

import { createPluginRegistration, GlobalStoreState } from '@embedpdf/core'
import { EmbedPDF } from '@embedpdf/core/react'
import { usePdfiumEngine } from '@embedpdf/engines/react'
import {
  Command,
  CommandsPluginPackage,
  useCommand,
} from '@embedpdf/plugin-commands/react'
import {
  DocumentManagerPluginPackage,
  DocumentContent,
} from '@embedpdf/plugin-document-manager/react'
import { RenderLayer, RenderPluginPackage } from '@embedpdf/plugin-render/react'
import {
  SCROLL_PLUGIN_ID,
  ScrollPlugin,
  ScrollPluginPackage,
  ScrollState,
  Scroller,
  useScroll,
} from '@embedpdf/plugin-scroll/react'
import {
  Viewport,
  VIEWPORT_PLUGIN_ID,
  ViewportPluginPackage,
  ViewportState,
} from '@embedpdf/plugin-viewport/react'
import {
  ZOOM_PLUGIN_ID,
  ZoomMode,
  ZoomPluginPackage,
  ZoomState,
} from '@embedpdf/plugin-zoom/react'
import {
  Loader2,
  ChevronLeft,
  ChevronRight,
  Info,
  Keyboard,
  type LucideIcon,
} from 'lucide-react'

export type State = GlobalStoreState<{
  [ZOOM_PLUGIN_ID]: ZoomState
  [VIEWPORT_PLUGIN_ID]: ViewportState
  [SCROLL_PLUGIN_ID]: ScrollState
}>

// Define Commands
const myCommands: Record<string, Command<State>> = {
  'nav.prev': {
    id: 'nav.prev',
    label: 'Previous Page',
    shortcuts: ['arrowleft', 'k'],
    action: ({ registry, documentId }) => {
      registry
        .getPlugin<ScrollPlugin>('scroll')
        ?.provides()
        ?.forDocument(documentId)
        .scrollToPreviousPage()
    },
    disabled: ({ state, documentId }) => {
      const scrollState = state.plugins.scroll.documents[documentId]
      return scrollState ? scrollState.currentPage <= 1 : true
    },
  },
  'nav.next': {
    id: 'nav.next',
    label: 'Next Page',
    shortcuts: ['arrowright', 'j'],
    action: ({ registry, documentId }) => {
      registry
        .getPlugin<ScrollPlugin>('scroll')
        ?.provides()
        ?.forDocument(documentId)
        .scrollToNextPage()
    },
    disabled: ({ state, documentId }) => {
      const scrollState = state.plugins.scroll.documents[documentId]
      return scrollState
        ? scrollState.currentPage >= scrollState.totalPages
        : true
    },
  },
  'doc.alert': {
    id: 'doc.alert',
    label: 'Show Info',
    shortcuts: ['ctrl+i', 'meta+i'],
    action: ({ state, documentId }) => {
      const page = state.plugins.scroll.documents[documentId]?.currentPage
      if (!page) return
      alert(`You are currently reading page ${page}`)
    },
  },
}

const plugins = [
  createPluginRegistration(DocumentManagerPluginPackage, {
    initialDocuments: [{ url: 'https://raw.githubusercontent.com/arnon3339/pubme/main/pdf/Digital_Inno_Cover.pdf' }],
  }),
  createPluginRegistration(ViewportPluginPackage),
  createPluginRegistration(ScrollPluginPackage),
  createPluginRegistration(RenderPluginPackage),
  createPluginRegistration(ZoomPluginPackage, {
    defaultZoomLevel: ZoomMode.FitPage,
  }),
  createPluginRegistration(CommandsPluginPackage, {
    commands: myCommands,
  }),
]

// Shortcut badge component
const ShortcutBadge = ({ shortcut }: { shortcut: string }) => {
  const formatted = shortcut
    .replace('arrowleft', '←')
    .replace('arrowright', '→')
    .replace('ctrl+', '⌃')
    .replace('meta+', '⌘')
    .toUpperCase()

  return (
    <kbd className="hidden items-center rounded border border-gray-300 bg-gray-200 px-1.5 py-0.5 font-mono text-[10px] font-medium text-gray-500 dark:border-gray-600 dark:bg-gray-700 dark:text-gray-300 sm:inline-flex">
      {formatted}
    </kbd>
  )
}

// Command Button Component
const CommandButton = ({
  commandId,
  documentId,
  icon: Icon,
  showLabel = true,
}: {
  commandId: string
  documentId: string
  icon?: LucideIcon
  showLabel?: boolean
}) => {
  const command = useCommand(commandId, documentId)

  if (!command) return null

  return (
    <button
      onClick={command.execute}
      disabled={command.disabled}
      className="inline-flex items-center gap-1.5 rounded-md bg-white px-2.5 py-1.5 text-xs font-medium text-gray-600 shadow-sm ring-1 ring-gray-300 transition-all hover:bg-gray-50 hover:text-gray-900 disabled:cursor-not-allowed disabled:opacity-40 dark:bg-gray-700 dark:text-gray-300 dark:ring-gray-600 dark:hover:bg-gray-600 dark:hover:text-gray-100"
      title={
        command.shortcuts
          ? `Shortcut: ${command.shortcuts.join(', ')}`
          : undefined
      }
    >
      {Icon && <Icon size={14} />}
      {showLabel && <span className="hidden sm:inline">{command.label}</span>}
      {command.shortcuts && command.shortcuts[0] && (
        <ShortcutBadge shortcut={command.shortcuts[0]} />
      )}
    </button>
  )
}

// Toolbar
const ViewerToolbar = ({ documentId }: { documentId: string }) => {
  const { state } = useScroll(documentId)

  return (
    <div className="flex items-center gap-3 border-b border-gray-300 bg-gray-100 px-3 py-2 dark:border-gray-700 dark:bg-gray-800">
      <div className="flex items-center gap-1.5 text-xs font-medium text-gray-600 dark:text-gray-300">
        <Keyboard size={14} />
        <span className="tracking-wide hidden uppercase sm:inline">
          Commands
        </span>
      </div>
      <div className="h-4 w-px bg-gray-300 dark:bg-gray-600" />

      {/* Navigation */}
      <div className="flex items-center gap-1">
        <CommandButton
          commandId="nav.prev"
          documentId={documentId}
          icon={ChevronLeft}
          showLabel={false}
        />

        {/* Page indicator */}
        <div className="min-w-[80px] rounded-md bg-white px-2 py-1 text-center shadow-sm ring-1 ring-gray-300 dark:bg-gray-700 dark:ring-gray-600">
          <span className="text-xs font-medium text-gray-700 dark:text-gray-300">
            {state.currentPage}{' '}
            <span className="text-gray-500 dark:text-gray-400">/</span>{' '}
            {state.totalPages}
          </span>
        </div>

        <CommandButton
          commandId="nav.next"
          documentId={documentId}
          icon={ChevronRight}
          showLabel={false}
        />
      </div>

      <div className="flex-1" />

      {/* Actions */}
      <CommandButton
        commandId="doc.alert"
        documentId={documentId}
        icon={Info}
      />

      {/* Hint */}
      <span className="hidden text-[10px] text-gray-600 dark:text-gray-300 lg:inline">
        Use keyboard shortcuts to navigate
      </span>
    </div>
  )
}

export const PDFViewer = () => {
  const { engine, isLoading } = usePdfiumEngine()

  if (isLoading || !engine) {
    return (
      <div className="overflow-hidden rounded-lg border border-gray-300 bg-white dark:border-gray-700 dark:bg-gray-900">
        <div className="flex h-[400px] items-center justify-center">
          <div className="flex items-center gap-2 text-gray-500 dark:text-gray-400">
            <Loader2 size={20} className="animate-spin" />
            <span className="text-sm">Loading PDF Engine...</span>
          </div>
        </div>
      </div>
    )
  }

  return (
    <EmbedPDF engine={engine} plugins={plugins}>
      {({ activeDocumentId }) =>
        activeDocumentId && (
          <DocumentContent documentId={activeDocumentId}>
            {({ isLoading: docLoading, isLoaded }) => (
              <>
                {docLoading && (
                  <div className="overflow-hidden rounded-lg border border-gray-300 bg-white dark:border-gray-700 dark:bg-gray-900">
                    <div className="flex h-[400px] items-center justify-center">
                      <div className="flex items-center gap-2 text-gray-500 dark:text-gray-400">
                        <Loader2 size={20} className="animate-spin" />
                        <span className="text-sm">Loading document...</span>
                      </div>
                    </div>
                  </div>
                )}
                {isLoaded && (
                  <div className="overflow-hidden rounded-lg border border-gray-300 bg-white shadow-sm dark:border-gray-700 dark:bg-gray-900">
                    {/* Toolbar */}
                    <ViewerToolbar documentId={activeDocumentId} />

                    {/* PDF Viewer Area */}
                    <div className="relative h-[400px] sm:h-[500px]">
                      <Viewport
                        documentId={activeDocumentId}
                        className="absolute inset-0 bg-gray-200 dark:bg-gray-800"
                      >
                        <Scroller
                          documentId={activeDocumentId}
                          renderPage={({ width, height, pageIndex }) => (
                            <div
                              style={{ width, height, position: 'relative' }}
                            >
                              <RenderLayer
                                documentId={activeDocumentId}
                                pageIndex={pageIndex}
                              />
                            </div>
                          )}
                        />
                      </Viewport>
                    </div>
                  </div>
                )}
              </>
            )}
          </DocumentContent>
        )
      }
    </EmbedPDF>
  )
}
