// examples/svelte-tailwind/src/routes/viewer/+page.svelte
<script lang="ts">
  import { EmbedPDF } from '@embedpdf/core/svelte';
  import { usePdfiumEngine } from '@embedpdf/engines/svelte';
  import { createPluginRegistration, PluginRegistry } from '@embedpdf/core';
  import { ViewportPluginPackage, Viewport } from '@embedpdf/plugin-viewport/svelte';
  import { ScrollPluginPackage, ScrollStrategy, Scroller } from '@embedpdf/plugin-scroll/svelte';
  import {
    DocumentManagerPluginPackage,
    DocumentContent,
    DocumentManagerPlugin,
  } from '@embedpdf/plugin-document-manager/svelte';
  import {
    InteractionManagerPluginPackage,
    GlobalPointerProvider,
    PagePointerProvider,
  } from '@embedpdf/plugin-interaction-manager/svelte';
  import { ZoomMode, ZoomPluginPackage, MarqueeZoom } from '@embedpdf/plugin-zoom/svelte';
  import { PanPluginPackage } from '@embedpdf/plugin-pan/svelte';
  import { SpreadMode, SpreadPluginPackage } from '@embedpdf/plugin-spread/svelte';
  import { Rotate, RotatePluginPackage } from '@embedpdf/plugin-rotate/svelte';
  import { RenderLayer, RenderPluginPackage } from '@embedpdf/plugin-render/svelte';
  import { TilingLayer, TilingPluginPackage } from '@embedpdf/plugin-tiling/svelte';
  import { ExportPluginPackage } from '@embedpdf/plugin-export/svelte';
  import { PrintPluginPackage } from '@embedpdf/plugin-print/svelte';
  import { SelectionLayer, SelectionPluginPackage } from '@embedpdf/plugin-selection/svelte';
  import { SearchLayer, SearchPluginPackage } from '@embedpdf/plugin-search/svelte';
  import { ThumbnailPluginPackage } from '@embedpdf/plugin-thumbnail/svelte';
  import { CapturePluginPackage, MarqueeCapture } from '@embedpdf/plugin-capture/svelte';
  import { FullscreenPluginPackage } from '@embedpdf/plugin-fullscreen/svelte';
  import { HistoryPluginPackage } from '@embedpdf/plugin-history/svelte';
  import {
    ViewManagerPluginPackage,
    ViewManagerPlugin,
  } from '@embedpdf/plugin-view-manager/svelte';
  import TabBarViewManager from '$lib/components/TabBarViewManager.svelte';
  import ViewerToolbar from '$lib/components/ViewerToolbar.svelte';
  import LoadingSpinner from '$lib/components/LoadingSpinner.svelte';
  import DocumentPasswordPrompt from '$lib/components/DocumentPasswordPrompt.svelte';
  import SearchSidebar from '$lib/components/SearchSidebar.svelte';
  import ThumbnailsSidebar from '$lib/components/ThumbnailsSidebar.svelte';
  import PageControls from '$lib/components/PageControls.svelte';
  import NavigationBar from '$lib/components/NavigationBar.svelte';
  import SplitViewLayout from '$lib/components/SplitViewLayout.svelte';
  import { ConsoleLogger } from '@embedpdf/models';
  import EmptyState from '$lib/components/EmptyState.svelte';
  import SelectionSelectionMenu from '$lib/components/SelectionSelectionMenu.svelte';

  const logger = new ConsoleLogger();

  const pdfEngine = usePdfiumEngine({ logger });

  // Track sidebar state per document
  type SidebarState = {
    search: boolean;
    thumbnails: boolean;
  };

  let sidebarStates = $state<Record<string, SidebarState>>({});

  const plugins = $derived.by(() => [
    createPluginRegistration(ViewportPluginPackage, {
      viewportGap: 10,
    }),
    createPluginRegistration(ScrollPluginPackage, {
      defaultStrategy: ScrollStrategy.Vertical,
    }),
    createPluginRegistration(DocumentManagerPluginPackage),
    createPluginRegistration(InteractionManagerPluginPackage),
    createPluginRegistration(ZoomPluginPackage, {
      defaultZoomLevel: ZoomMode.FitPage,
    }),
    createPluginRegistration(PanPluginPackage),
    createPluginRegistration(SpreadPluginPackage, {
      defaultSpreadMode: SpreadMode.None,
    }),
    createPluginRegistration(RotatePluginPackage),
    createPluginRegistration(ExportPluginPackage),
    createPluginRegistration(PrintPluginPackage),
    createPluginRegistration(RenderPluginPackage),
    createPluginRegistration(TilingPluginPackage, {
      tileSize: 768,
      overlapPx: 2.5,
      extraRings: 0,
    }),
    createPluginRegistration(SelectionPluginPackage),
    createPluginRegistration(SearchPluginPackage),
    createPluginRegistration(CapturePluginPackage),
    createPluginRegistration(HistoryPluginPackage),
    createPluginRegistration(FullscreenPluginPackage, {
      targetElement: '#document-content',
    }),
    createPluginRegistration(ThumbnailPluginPackage, {
      width: 120,
      paddingY: 10,
    }),
    createPluginRegistration(ViewManagerPluginPackage, {
      defaultViewCount: 1,
    }),
  ]);

  const toggleSidebar = (documentId: string, sidebar: keyof SidebarState) => {
    sidebarStates = {
      ...sidebarStates,
      [documentId]: {
        ...(sidebarStates[documentId] || { search: false, thumbnails: false }),
        [sidebar]: !sidebarStates[documentId]?.[sidebar],
      },
    };
  };

  const getSidebarState = (documentId: string): SidebarState => {
    return sidebarStates[documentId] || { search: false, thumbnails: false };
  };

  const handleInitialized = async (registry: PluginRegistry) => {
    // Load default PDF URL on initialization
    const document = await registry
      .getPlugin<DocumentManagerPlugin>(DocumentManagerPlugin.id)
      ?.provides()
      ?.openDocumentUrl({
        url: 'https://raw.githubusercontent.com/arnon3339/pubme/main/pdf/Digital_Inno_Cover.pdf',
      })
      .toPromise();

    if (!document) return;

    const viewManager = registry.getPlugin<ViewManagerPlugin>(ViewManagerPlugin.id)?.provides();
    if (!viewManager) return;

    const views = viewManager.getAllViews();
    if (views.length > 0 && views[0]) {
      const firstViewId = views[0].id;
      viewManager.addDocumentToView(firstViewId, document.documentId);
      viewManager.setViewActiveDocument(firstViewId, document.documentId);
    }
  };

  const openFileDialog = (registry: PluginRegistry, context: any) => {
    const openTask = registry
      .getPlugin<DocumentManagerPlugin>(DocumentManagerPlugin.id)
      ?.provides()
      ?.openFileDialog();
    openTask?.wait(
      (result) => {
        context.addDocument(result.documentId);
        context.setActiveDocument(result.documentId);
      },
      (error) => {
        console.error('Open file failed:', error);
      },
    );
  };
</script>

{#if pdfEngine.error}
  <div class="flex h-screen items-center justify-center">
    <div>Error: {pdfEngine.error.message}</div>
  </div>
{:else if pdfEngine.isLoading || !pdfEngine.engine}
  <div class="flex h-screen items-center justify-center">
    <LoadingSpinner message="Loading PDF engine..." />
  </div>
{:else}
  <div class="flex h-screen flex-1 flex-col overflow-hidden">
    <NavigationBar />

    <div class="flex flex-1 select-none flex-col overflow-hidden">
      <EmbedPDF engine={pdfEngine.engine} {logger} {plugins} onInitialized={handleInitialized}>
        {#snippet children({ pluginsReady, registry })}
          {#if !pluginsReady}
            <div class="flex h-full items-center justify-center">
              <LoadingSpinner message="Initializing plugins..." />
            </div>
          {:else}
            <SplitViewLayout>
              {#snippet renderView({ context })}
                <div class="flex h-full flex-col">
                  <TabBarViewManager
                    currentView={context.view}
                    onSelect={(documentId) => context.setActiveDocument(documentId)}
                    onClose={(docId) =>
                      registry
                        ?.getPlugin<DocumentManagerPlugin>(DocumentManagerPlugin.id)
                        ?.provides()
                        ?.closeDocument(docId)}
                    onOpenFile={() => (registry ? openFileDialog(registry, context) : undefined)}
                  />

                  {#if context.activeDocumentId}
                    {@const documentId = context.activeDocumentId}
                    <ViewerToolbar
                      {documentId}
                      onToggleSearch={() => toggleSidebar(documentId, 'search')}
                      onToggleThumbnails={() => toggleSidebar(documentId, 'thumbnails')}
                      isSearchOpen={getSidebarState(documentId).search}
                      isThumbnailsOpen={getSidebarState(documentId).thumbnails}
                    />
                  {/if}

                  <!-- Empty State - No Documents -->
                  {#if !context.activeDocumentId}
                    <EmptyState
                      onDocumentOpened={(documentId) => {
                        context.addDocument(documentId);
                        context.setActiveDocument(documentId);
                      }}
                    />
                  {/if}

                  <!-- Document Content Area -->
                  {#if context.activeDocumentId}
                    {@const documentId = context.activeDocumentId}
                    <div id="document-content" class="flex flex-1 overflow-hidden bg-white">
                      <!-- Thumbnails Sidebar - Left -->
                      {#if getSidebarState(documentId).thumbnails}
                        <ThumbnailsSidebar {documentId} />
                      {/if}

                      <!-- Main Viewer -->
                      <div class="flex-1 overflow-hidden">
                        <DocumentContent documentId={context.activeDocumentId}>
                          {#snippet children({ documentState, isLoading, isError, isLoaded })}
                            {#if isLoading}
                              <div class="flex h-full items-center justify-center">
                                <LoadingSpinner message="Loading document..." />
                              </div>
                            {:else if isError}
                              <DocumentPasswordPrompt {documentState} />
                            {:else if isLoaded}
                              <div class="relative h-full w-full">
                                <GlobalPointerProvider {documentId}>
                                  <Viewport class="bg-gray-100" {documentId}>
                                    <Scroller {documentId}>
                                      {#snippet renderPage(page)}
                                        <Rotate
                                          {documentId}
                                          pageIndex={page.pageIndex}
                                          style="background-color: #fff"
                                        >
                                          <PagePointerProvider
                                            {documentId}
                                            pageIndex={page.pageIndex}
                                          >
                                            <RenderLayer
                                              {documentId}
                                              pageIndex={page.pageIndex}
                                              scale={1}
                                              style="pointer-events: none"
                                            />
                                            <SearchLayer {documentId} pageIndex={page.pageIndex} />
                                            <MarqueeZoom {documentId} pageIndex={page.pageIndex} />
                                            <MarqueeCapture
                                              {documentId}
                                              pageIndex={page.pageIndex}
                                            />
                                            <SelectionLayer {documentId} pageIndex={page.pageIndex}>
                                              {#snippet selectionMenuSnippet(props)}
                                                <SelectionSelectionMenu {...props} {documentId} />
                                              {/snippet}
                                            </SelectionLayer>
                                          </PagePointerProvider>
                                        </Rotate>
                                      {/snippet}
                                    </Scroller>
                                    <!-- Page Controls -->
                                    <PageControls {documentId} />
                                  </Viewport>
                                </GlobalPointerProvider>
                              </div>
                            {/if}
                          {/snippet}
                        </DocumentContent>
                      </div>

                      <!-- Search Sidebar - Right -->
                      {#if getSidebarState(context.activeDocumentId).search}
                        <SearchSidebar {documentId} />
                      {/if}
                    </div>
                  {/if}
                </div>
              {/snippet}
            </SplitViewLayout>
          {/if}
        {/snippet}
      </EmbedPDF>
    </div>
  </div>
{/if}

// examples/react-tailwind/src/pages/viewer.tsx
import { useMemo, useRef, useState } from 'react';
import {
  dutchTranslations,
  englishTranslations,
  germanTranslations,
  paramResolvers,
  spanishTranslations,
  thaiTranslations,
} from '../config/translations';
import { EmbedPDF } from '@embedpdf/core/react';
import { usePdfiumEngine } from '@embedpdf/engines/react';
import { createPluginRegistration } from '@embedpdf/core';
import { ViewportPluginPackage, Viewport } from '@embedpdf/plugin-viewport/react';
import { ScrollPluginPackage, ScrollStrategy, Scroller } from '@embedpdf/plugin-scroll/react';
import {
  DocumentManagerPluginPackage,
  DocumentContent,
  DocumentManagerPlugin,
} from '@embedpdf/plugin-document-manager/react';
import {
  InteractionManagerPluginPackage,
  GlobalPointerProvider,
  PagePointerProvider,
} from '@embedpdf/plugin-interaction-manager/react';
import { ZoomMode, ZoomPluginPackage, MarqueeZoom } from '@embedpdf/plugin-zoom/react';
import { PanPluginPackage } from '@embedpdf/plugin-pan/react';
import { SpreadMode, SpreadPluginPackage } from '@embedpdf/plugin-spread/react';
import { Rotate, RotatePluginPackage } from '@embedpdf/plugin-rotate/react';
import { RenderLayer, RenderPluginPackage } from '@embedpdf/plugin-render/react';
import { TilingLayer, TilingPluginPackage } from '@embedpdf/plugin-tiling/react';
import { ViewManagerPlugin, ViewManagerPluginPackage } from '@embedpdf/plugin-view-manager/react';
import { RedactionLayer, RedactionPluginPackage } from '@embedpdf/plugin-redaction/react';
import { ExportPluginPackage } from '@embedpdf/plugin-export/react';
import { PrintPluginPackage } from '@embedpdf/plugin-print/react';
import { SelectionLayer, SelectionPluginPackage } from '@embedpdf/plugin-selection/react';
import { SearchLayer, SearchPluginPackage } from '@embedpdf/plugin-search/react';
import { ThumbnailPluginPackage } from '@embedpdf/plugin-thumbnail/react';
import { CapturePluginPackage, MarqueeCapture } from '@embedpdf/plugin-capture/react';
import { FullscreenPluginPackage } from '@embedpdf/plugin-fullscreen/react';
import { HistoryPluginPackage } from '@embedpdf/plugin-history/react';
import { AnnotationPluginPackage, AnnotationLayer } from '@embedpdf/plugin-annotation/react';
import { TabBar } from '../components/tab-bar';
import { ViewerToolbar, ViewMode } from '../components/viewer-toolbar';
import { LoadingSpinner } from '../components/loading-spinner';
import { DocumentPasswordPrompt } from '../components/document-password-prompt';
import { SearchSidebar } from '../components/search-sidebar';
import { ThumbnailsSidebar } from '../components/thumbnails-sidebar';
import { PageControls } from '../components/page-controls';
import { ConsoleLogger } from '@embedpdf/models';
import { SplitViewLayout } from '../components/split-view-layout';
import { AnnotationSelectionMenu } from '../components/annotation-selection-menu';
import { SelectionSelectionMenu } from '../components/selection-selection-menu';
import { NavigationBar } from '../components/navigation-bar';
import { EmptyState } from '../components/empty-state';
import { I18nPluginPackage } from '@embedpdf/plugin-i18n/react';
import { RedactionSelectionMenu } from '../components/redaction-selection-menu';

const logger = new ConsoleLogger();

// Type for tracking sidebar state per document
type SidebarState = {
  search: boolean;
  thumbnails: boolean;
};

// Helper to detect system language and match with available locales
const detectSystemLanguage = (availableLocales: string[]): string => {
  if (typeof navigator === 'undefined') return 'en-US';

  const systemLocales = (navigator.languages && navigator.languages.length) ? navigator.languages : [navigator.language || 'en-US'];
  for (const locale of systemLocales) {
    if (!locale) continue;
    // Try exact match (e.g. 'th-TH' -> 'th-TH')
    if (availableLocales.includes(locale)) return locale;

    // Try language code match (e.g. 'th-TH' -> 'th')
    const langCode = locale.split('-')[0];
    if (langCode && availableLocales.includes(langCode)) return langCode;
  }

  return 'en-US'; // Fallback
};

export function ViewerPage() {
  const containerRef = useRef<HTMLDivElement>(null);
  const { engine, isLoading, error } = usePdfiumEngine({
    logger,
  });

  // Track sidebar state per document
  const [sidebarStates, setSidebarStates] = useState<Record<string, SidebarState>>({});

  // Track toolbar mode per document
  const [toolbarModes, setToolbarModes] = useState<Record<string, ViewMode>>({});

  const plugins = useMemo(
    () => [
      createPluginRegistration(ViewportPluginPackage, {
        viewportGap: 10,
      }),
      createPluginRegistration(ScrollPluginPackage, {
        defaultStrategy: ScrollStrategy.Vertical,
      }),
      createPluginRegistration(DocumentManagerPluginPackage),
      createPluginRegistration(InteractionManagerPluginPackage),
      createPluginRegistration(ZoomPluginPackage, {
        defaultZoomLevel: ZoomMode.FitPage,
      }),
      createPluginRegistration(PanPluginPackage),
      createPluginRegistration(SpreadPluginPackage, {
        defaultSpreadMode: SpreadMode.None,
      }),
      createPluginRegistration(RotatePluginPackage),
      createPluginRegistration(ExportPluginPackage),
      createPluginRegistration(PrintPluginPackage),
      createPluginRegistration(RenderPluginPackage),
      createPluginRegistration(TilingPluginPackage, {
        tileSize: 768,
        overlapPx: 2.5,
        extraRings: 0,
      }),
      createPluginRegistration(SelectionPluginPackage),
      createPluginRegistration(SearchPluginPackage),
      createPluginRegistration(RedactionPluginPackage),
      createPluginRegistration(CapturePluginPackage),
      createPluginRegistration(HistoryPluginPackage),
      createPluginRegistration(AnnotationPluginPackage),
      createPluginRegistration(FullscreenPluginPackage, {
        targetElement: '#document-content',
      }),
      createPluginRegistration(ThumbnailPluginPackage, {
        width: 120,
        paddingY: 10,
      }),
      createPluginRegistration(ViewManagerPluginPackage, {
        defaultViewCount: 1,
      }),
      createPluginRegistration(I18nPluginPackage, {
        defaultLocale: detectSystemLanguage(['en-US', 'th']), // Add other supported locales here
        locales: [
          englishTranslations,
          spanishTranslations,
          germanTranslations,
          dutchTranslations,
          thaiTranslations,
        ],
        paramResolvers,
      }),
    ],
    [], // Empty dependency array since these never change
  );

  const toggleSidebar = (documentId: string, sidebar: keyof SidebarState) => {
    setSidebarStates((prev) => ({
      ...prev,
      [documentId]: {
        ...(prev[documentId] || { search: false, thumbnails: false }),
        [sidebar]: !prev[documentId]?.[sidebar],
      },
    }));
  };

  const getSidebarState = (documentId: string): SidebarState => {
    return sidebarStates[documentId] || { search: false, thumbnails: false };
  };

  const getToolbarMode = (documentId: string): ViewMode => {
    return toolbarModes[documentId] || 'view';
  };

  const setToolbarMode = (documentId: string, mode: ViewMode) => {
    setToolbarModes((prev) => ({
      ...prev,
      [documentId]: mode,
    }));
  };

  if (error) {
    return <div>Error: {error.message}</div>;
  }

  if (isLoading || !engine) {
    return (
      <div className="flex h-screen items-center justify-center">
        <LoadingSpinner message="Loading PDF engine..." />
      </div>
    );
  }

  return (
    <div className="flex h-screen flex-1 flex-col overflow-hidden" ref={containerRef}>
      <NavigationBar />

      <div className="flex flex-1 select-none flex-col overflow-hidden">
        <EmbedPDF
          engine={engine}
          logger={logger}
          plugins={plugins}
          onInitialized={async (registry) => {
            // Load default PDF URL on initialization
            const document = await registry
              ?.getPlugin<DocumentManagerPlugin>(DocumentManagerPlugin.id)
              ?.provides()
              ?.openDocumentUrl({ url: 'https://raw.githubusercontent.com/arnon3339/pubme/main/pdf/Digital_Inno_Cover.pdf' })
              .toPromise();

            if (!document) return;

            const viewManager = registry
              ?.getPlugin<ViewManagerPlugin>(ViewManagerPlugin.id)
              ?.provides();
            if (!viewManager) return;

            const views = viewManager.getAllViews();
            if (views.length > 0 && views[0]) {
              const firstViewId = views[0].id;
              viewManager.addDocumentToView(firstViewId, document.documentId);
              viewManager.setViewActiveDocument(firstViewId, document.documentId);
            }
          }}
        >
          {({ pluginsReady, registry }) => (
            <>
              {pluginsReady ? (
                <SplitViewLayout
                  renderView={({
                    view,
                    activeDocumentId: documentId,
                    addDocument,
                    setActiveDocument,
                  }) => (
                    <div className="flex h-full flex-col">
                      <TabBar
                        currentView={view}
                        onSelect={(documentId) => setActiveDocument(documentId)}
                        onClose={(docId) =>
                          registry
                            ?.getPlugin<DocumentManagerPlugin>(DocumentManagerPlugin.id)
                            ?.provides()
                            ?.closeDocument(docId)
                        }
                        onOpenFile={() => {
                          const openTask = registry
                            ?.getPlugin<DocumentManagerPlugin>(DocumentManagerPlugin.id)
                            ?.provides()
                            ?.openFileDialog();
                          openTask?.wait(
                            (result) => {
                              addDocument(result.documentId);
                              setActiveDocument(result.documentId);
                            },
                            (error) => {
                              console.error('Open file failed:', error);
                            },
                          );
                        }}
                      />

                      {documentId && (
                        <ViewerToolbar
                          documentId={documentId}
                          onToggleSearch={() => toggleSidebar(documentId, 'search')}
                          onToggleThumbnails={() => toggleSidebar(documentId, 'thumbnails')}
                          isSearchOpen={getSidebarState(documentId).search}
                          isThumbnailsOpen={getSidebarState(documentId).thumbnails}
                          mode={getToolbarMode(documentId)}
                          onModeChange={(mode) => setToolbarMode(documentId, mode)}
                        />
                      )}

                      {/* Empty State - No Documents */}
                      {!documentId && (
                        <EmptyState
                          onDocumentOpened={(documentId) => {
                            addDocument(documentId);
                            setActiveDocument(documentId);
                          }}
                        />
                      )}

                      {/* Document Content Area */}
                      {documentId && (
                        <div id={documentId} className="flex flex-1 overflow-hidden bg-white">
                          {/* Thumbnails Sidebar - Left */}
                          {getSidebarState(documentId).thumbnails && (
                            <ThumbnailsSidebar
                              documentId={documentId}
                              onClose={() => toggleSidebar(documentId, 'thumbnails')}
                            />
                          )}

                          {/* Main Viewer */}
                          <div className="flex-1 overflow-hidden">
                            <DocumentContent documentId={documentId}>
                              {({ documentState, isLoading, isError, isLoaded }) => (
                                <>
                                  {isLoading && (
                                    <div className="flex h-full items-center justify-center">
                                      <LoadingSpinner message="Loading document..." />
                                    </div>
                                  )}
                                  {isError && (
                                    <DocumentPasswordPrompt documentState={documentState} />
                                  )}
                                  {isLoaded && (
                                    <div className="relative h-full w-full">
                                      <GlobalPointerProvider documentId={documentId}>
                                        <Viewport className="bg-gray-100" documentId={documentId}>
                                          <Scroller
                                            documentId={documentId}
                                            renderPage={({ pageIndex }) => (
                                              <Rotate
                                                documentId={documentId}
                                                pageIndex={pageIndex}
                                                style={{ backgroundColor: '#fff' }}
                                              >
                                                <PagePointerProvider
                                                  documentId={documentId}
                                                  pageIndex={pageIndex}
                                                >
                                                  <RenderLayer
                                                    documentId={documentId}
                                                    pageIndex={pageIndex}
                                                    scale={1}
                                                    style={{ pointerEvents: 'none' }}
                                                  />
                                                  <TilingLayer
                                                    documentId={documentId}
                                                    pageIndex={pageIndex}
                                                    style={{ pointerEvents: 'none' }}
                                                  />
                                                  <SearchLayer
                                                    documentId={documentId}
                                                    pageIndex={pageIndex}
                                                  />
                                                  <MarqueeZoom
                                                    documentId={documentId}
                                                    pageIndex={pageIndex}
                                                  />
                                                  <MarqueeCapture
                                                    documentId={documentId}
                                                    pageIndex={pageIndex}
                                                  />
                                                  <SelectionLayer
                                                    documentId={documentId}
                                                    pageIndex={pageIndex}
                                                    selectionMenu={(props) => (
                                                      <SelectionSelectionMenu
                                                        {...props}
                                                        documentId={documentId}
                                                      />
                                                    )}
                                                  />
                                                  <RedactionLayer
                                                    documentId={documentId}
                                                    pageIndex={pageIndex}
                                                    selectionMenu={(props) => (
                                                      <RedactionSelectionMenu
                                                        {...props}
                                                        documentId={documentId}
                                                      />
                                                    )}
                                                  />
                                                  <AnnotationLayer
                                                    documentId={documentId}
                                                    pageIndex={pageIndex}
                                                    selectionMenu={(props) => (
                                                      <AnnotationSelectionMenu
                                                        {...props}
                                                        documentId={documentId}
                                                      />
                                                    )}
                                                  />
                                                </PagePointerProvider>
                                              </Rotate>
                                            )}
                                          />
                                          {/* Page Controls */}
                                          <PageControls documentId={documentId} />
                                        </Viewport>
                                      </GlobalPointerProvider>
                                    </div>
                                  )}
                                </>
                              )}
                            </DocumentContent>
                          </div>

                          {/* Search Sidebar - Right */}
                          {getSidebarState(documentId).search && (
                            <SearchSidebar
                              documentId={documentId}
                              onClose={() => toggleSidebar(documentId, 'search')}
                            />
                          )}
                        </div>
                      )}
                    </div>
                  )}
                />
              ) : (
                <div className="flex h-full items-center justify-center">
                  <LoadingSpinner message="Initializing plugins..." />
                </div>
              )}
            </>
          )}
        </EmbedPDF>
      </div>
    </div>
  );
}
